name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Set permissions
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies 
        run: npm ci

      - name: Get Repository Info 
        id: repo-info
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
          echo "REPO_OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)" >> $GITHUB_ENV
          echo "Repository name: ${{ env.REPO_NAME }}"
          echo "Repository owner: ${{ env.REPO_OWNER }}"

      - name: Build 
        run: |
          # Create env-config.js file for GitHub Pages
          mkdir -p public
          echo '
            // Runtime environment variables for GitHub Pages
            window._env_ = window._env_ || {};
            window._env_.SUPABASE_URL = "${{ secrets.VITE_SUPABASE_URL }}";
            window._env_.SUPABASE_ANON_KEY = "${{ secrets.VITE_SUPABASE_ANON_KEY }}";
            window._env_.OPENROUTER_API_KEY = "${{ secrets.VITE_OPENROUTER_API_KEY }}";
          ' > public/env-config.js
          
          # Build the application
          npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_OPENROUTER_API_KEY: ${{ secrets.VITE_OPENROUTER_API_KEY }}
          # Add GitHub Pages URL for proper base path configuration
          PUBLIC_URL: https://${{ env.REPO_OWNER }}.github.io/${{ env.REPO_NAME }}
          VITE_PUBLIC_PATH: /${{ env.REPO_NAME }}/

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages 